#!/opt/local/bin/perl

use strict;
use warnings;
use Data::Dumper;
use lib "/home/pi/perl5/lib/perl5";
use JSON "decode_json";
use RRD::Simple;

# could use HTTP::Tiny rather than curl...

my $structure = $ARGV[0];
my $thermostat = $ARGV[1];
my $away = "";
my $newaway = "U";
my $target = "U";
my $ambient = "U";
my $humidity = "U";
my $rrd = RRD::Simple->new( file => "/home/pi/Nest/thermostat.rrd" );
my $heartbeat = 600;

open(EVENTLOG, ">>thermometer.evt") || die;
select(EVENTLOG); $| = 1;
select(STDOUT); $| = 1;

sub event {
	printf(EVENTLOG "%d %s\n", time(), $_[0]);
}

sub timestamp {
	print STDOUT localtime() . ": " . $_[0] . "\n";
}

sub rrdupdate {
	$rrd->update( Target_temp => $target, Ambient_temp => $ambient, 
		      Humidity => $humidity, Away => ($newaway ne "home"));
	alarm($heartbeat);
	sleep(1);
}

$SIG{ALRM} = sub { rrdupdate() ; timestamp("timer-trigerred RRD update") };
timestamp("--start--");
alarm($heartbeat);
while (<STDIN>) {
	chomp();
	# only respond to events
	/^event:\ (\S+)/ || next;
	if ($1 eq 'put') {
		my $data = <STDIN>;
		$data =~ s/^data:\ //;

		my $hash = decode_json($data);
		$newaway = $hash->{data}->{structures}->{$structure}->{away};
		$ambient = $hash->{data}->{devices}->{thermostats}->{$thermostat}->{ambient_temperature_c};
		$target = $hash->{data}->{devices}->{thermostats}->{$thermostat}->{target_temperature_c};
		$humidity = $hash->{data}->{devices}->{thermostats}->{$thermostat}->{humidity};
		rrdupdate();
		if ($away) {
			if ($away ne $newaway) {
				event($newaway);
				timestamp("change away=$newaway");
			}
		} else {
			timestamp("initalise away=$newaway");
		}
		$away = $newaway;
	} elsif ($1 eq "keep-alive") {
		# don't log keep-alives
		my $data = <STDIN>;
		next;
	}
	my $s = sprintf("N:%.1f:%.1f:%.1f:%d", $ambient, $target, $humidity, $away ne "home");
	timestamp("$1 $s");
}
timestamp("--stop--");
close(EVENTLOG);
