#!/opt/local/bin/perl

use strict;
use warnings;
use Data::Dumper;
use lib "/home/pi/perl5/lib/perl5";

print localtime() . ": --start--\n";
open(OUT, ">>nest-streaming.json") || die;

sub lock {
	flock(OUT, 2);
	seek(OUT, 0, 0);
	truncate(OUT, 0);
}

sub unlock {
	flock(OUT, 8);
}	
	
while (<STDIN>) {
	chomp();
	# only respond to events
	/^event:\ (\S+)/ || next;
	if ($1 eq 'put') {
		my $data = <STDIN>;
		$data =~ s/^data:\ //;

		lock();
		print OUT $data;
		unlock();

	} elsif ($1 eq "keep-alive") {
		# don't log keep-alives
		next;
	}
	print localtime() . ": $1\n";
}
print localtime() . ": --stop--\n";
